### ISSUE TITLE
Interested in the performance of 3D instance segmentation

### ISSUE THREAD

**Issue by RayYoh** [filaPro/unidet3d#1]
Hi authors,

Thanks for your great work! I'd like to ask have you ever tested the performance of this transformer encoder-only model for 3D instance segmentation compared with Oneformer3D.

Best

**Comment by filaPro** [comment]
Hi @RayYoh ,
Actually, as we don't use query selection on inference for OneFormer3D on Scannet, all cross attentions there can be imagined as self attention. Like if for some scene we have 1000 superpoints, than we have 1000 queries from them, and 1000 keys and values also from them. So basically it is the same architecture, and we just refactored it and claim as encoder-only in UniDet3D. For OneFormer3D on S3DIS it is a little bit another story.
