### ISSUE TITLE
Obtain superpoints from custom dataset

### ISSUE THREAD

**Issue by LIP773** [filaPro/unidet3d#11]
Hello authors！If I want to obtain superpoints from my point cloud dataset([x, y, z, r, g, b] format), can I generate triangles (such as commonly used Poisson Surface Reconstruction or Greedy Triangulation) based on the coordinate information of the point cloud, and then use `segmenter. segmenter_mesh (coords, triangles)` to obtain superpoints? Although this method may seem to bring some bias.

**Comment by filaPro** [comment]
Yes, it should be fine. We use this ScanNet segmentator for 2 datasets, and [superpoint_transformer](https://github.com/drprojects/superpoint_transformer) for remaining 4.
