### ISSUE TITLE
Question about performance on SUNRGBD

### ISSUE THREAD

**Issue by linQian99** [filaPro/unidet3d#2]
Dear author,

Thank you for your great work! May I ask do you have plan of test on SUNRGBD? Thank you

Best Regards,
Lin Qian

**Comment by filaPro** [comment]
Hi @linQian99 ,

Unfortunately no. As we point out in our paper a scene of SUN RGB-D dataset is defines by a *single* rgb-d image, unlike our 6 datasets, where a scene is a point cloud reconstructed from *multiple* rgb-d images. We think that training a single model on these two modalities is not a good idea. However the architecture itself trained only on SUN RGB-D may work fine, if you tune superpoint clustering properly.

**Comment by azztt** [comment]
May I please ask how I can prepare SUN RGB-D for this architecture?

**Comment by filaPro** [comment]
I think, you can follow preprocessing in [SPGroup3D](https://github.com/zyrant/SPGroup3D/tree/main/data/sunrgbd).
