### ISSUE TITLE
custom_imports  Import issues

### ISSUE THREAD

**Issue by xwmxcz** [filaPro/unidet3d#3]
Thank you for your contribution, but when I reproduced the ScanNet single data set training, the situation shown in the screenshot occurred. What happened? Thank you for your answer.
![image](https://github.com/user-attachments/assets/37b1cb1e-8de8-4798-86d0-4447e9850886)

**Comment by filaPro** [comment]
Can you please provide the command you are running and the full output?
Also I see `/data/coding/unidet3d-master/mmdetection3d` in your log. You should not install mmdetection3d in this way, only through pip.
