### ISSUE TITLE
Could you please provide a configuration file specifically for training on the S3DIS dataset?

### ISSUE THREAD

**Issue by Yuehongzhe** [filaPro/unidet3d#5]
This is an interesting work. Could you please provide a configuration file specifically for training on the S3DIS dataset? Thank you very much.

**Comment by filaPro** [comment]
I don't have the one only for S3DIS. But can you get `diff` between our 6 datasets config and ScanNet config and try to make the same thing for S3DIS?

**Comment by Wang-hui-001** [comment]
Hello, do you have the single-dataset configuration file for S3DIS?
