### ISSUE TITLE
Parameters which did not receive grad for rank 1: decoder.out_bboxes.linear.bias, decoder.out_bboxes.linear.weight 

### ISSUE THREAD

**Issue by yxchng** [filaPro/unidet3d#8]
why this error happen during training?

**Comment by filaPro** [comment]
please provide the command you are running and a full output log

**Comment by yxchng** [comment]
`./tools/dist_train.sh configs/unidet3d_1xb8_scannet_s3dis_multiscan_3rscan_scannetpp_arkitscenes.p
y 8`

it will occurs halfway into the training

`11/19 23:23:52 - mmengine - INFO - Saving checkpoint at 486 epochs                                                                               [130/1804]
[rank4]: Traceback (most recent call last):                                                                                                                
[rank4]:   File "./tools/train.py", line 135, in <module>                                                                                                  
[rank4]:     main()                                                                                                                                        
[rank4]:   File "./tools/train.py", line 131, in main                                                                                                      
[rank4]:     runner.train()                                                                                                                                
[rank4]:   File "/fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/cyg1sgh/cache/conda/envs/unidet3d/lib/python3.8/site-packages/mmengine/runner/ru$
ner.py", line 1777, in train                                                                                                                               
[rank4]:     model = self.train_loop.run()  # type: ignore                                                                                                 
[rank4]:   File "/fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/cyg1sgh/cache/conda/envs/unidet3d/lib/python3.8/site-packages/mmengine/runner/lo$
ps.py", line 98, in run                                                                                                                                    
[rank4]:     self.run_epoch()                                                                                                                              
[rank4]:   File "/fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/cyg1sgh/cache/conda/envs/unidet3d/lib/python3.8/site-packages/mmengine/runner/loo
ps.py", line 115, in run_epoch
[rank4]:     self.run_iter(idx, data_batch)
[rank4]:   File "/fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/cyg1sgh/cache/conda/envs/unidet3d/lib/python3.8/site-packages/mmengine/runner/loo
ps.py", line 131, in run_iter
[rank4]:     outputs = self.runner.model.train_step(
[rank4]:   File "/fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/cyg1sgh/cache/conda/envs/unidet3d/lib/python3.8/site-packages/mmengine/model/wrap
pers/distributed.py", line 121, in train_step
[rank4]:     losses = self._run_forward(data, mode='loss')
[rank4]:   File "/fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/cyg1sgh/cache/conda/envs/unidet3d/lib/python3.8/site-packages/mmengine/model/wrap
pers/distributed.py", line 161, in _run_forward
[rank4]:     results = self(**data, mode=mode)
[rank4]:   File "/fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/cyg1sgh/cache/conda/envs/unidet3d/lib/python3.8/site-packages/torch/nn/modules/mo
dule.py", line 1553, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/cyg1sgh/cache/conda/envs/unidet3d/lib/python3.8/site-packages/torch/nn/modules/mo
dule.py", line 1562, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/cyg1sgh/cache/conda/envs/unidet3d/lib/python3.8/site-packages/torch/nn/parallel/d
istributed.py", line 1632, in forward
[rank4]:     inputs, kwargs = self._pre_forward(*inputs, **kwargs)
[rank4]:   File "/fs/scratch/rb_bd_dlp_rng-dl01_cr_ROB_employees/students/cyg1sgh/cache/conda/envs/unidet3d/lib/python3.8/site-packages/torch/nn/parallel/d
istributed.py", line 1523, in _pre_forward
[rank4]:     if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
[rank4]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has para
meters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `to
rch.nn.parallel.DistributedDataParallel`, and by
[rank4]: making sure all `forward` function outputs participate in calculating loss.
[rank4]: If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your
 module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue
(e.g. list, dict, iterable).
[rank4]: Parameter indices which did not receive grad for rank 4: 529 530
[rank4]:  In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particula
r parameters did not receive gradient on this rank as part of this error
W1119 23:25:20.007454 23287286421312 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 185073 closing signal SIGTERM`

**Comment by filaPro** [comment]
Are you training on multiple GPUs? I think we recommend training on one. As written in your log this problem can be fixed with `find_unused_parameters=True`. Please see https://mmengine.readthedocs.io/en/v0.8.4/common_usage/debug_tricks.html#find-unused-parameters.

**Comment by yxchng** [comment]
yes i am training on multiple gpus, do you have any idea why sometimes it gets this error?

**Comment by filaPro** [comment]
i think, we handle scenes from some datasets with 0 gt boxes. if some batch on some GPU contains only such scenes, that there will be None gradient for last regression linear layer. it should be carefully replaced with 0 loss, adding one `if` statement, like [here](https://github.com/SamsungLabs/tr3d/blob/main/mmdet3d/models/dense_heads/fcaf3d_head.py#L320)

**Comment by filaPro** [comment]
It is this [line](https://github.com/filaPro/unidet3d/blob/master/unidet3d/criterion.py#L138). Can you please replace this 0 to some analog of 0 but with valid gradients? E.g. `torch.cat(pred_bboxes).sum() * 0` or `pred_bboxes[0][:0, :0]` etc.

**Comment by CodeWZT** [comment]
> `./tools/dist_train.sh configs/unidet3d_1xb8_scannet_s3dis_multiscan_3rscan_scannetpp_arkitscenes.p y 8`
> 
> it will occurs halfway into the training
> 
> ` 11/19 23:23:52 - mmengine - INFO - Saving checkpoint at 486 epochs
> 
> [rank4]: Traceback (most recent call last): [rank4]: File "./tools/train.py", line 135, in [rank4]: main() [rank4]: File "./tools/train.py", line 131, in main [rank4]: runner.train() [rank4]: File "/home/user/cache/conda/envs/unidet3d/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train [rank4]: model = self.train_loop.run() # type: ignore [rank4]: File "/home/user/cache/conda/envs/unidet3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 98, in run [rank4]: self.run_epoch() [rank4]: File "/home/user/cache/conda/envs/unidet3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 115, in run_epoch [rank4]: self.run_iter(idx, data_batch) [rank4]: File "/home/user/cache/conda/envs/unidet3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 131, in run_iter [rank4]: outputs = self.runner.model.train_step( [rank4]: File "/home/user/cache/conda/envs/unidet3d/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 121, in train_step [rank4]: losses = self._run_forward(data, mode='loss') [rank4]: File "/home/user/cache/conda/envs/unidet3d/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 161, in _run_forward [rank4]: results = self(**data, mode=mode) [rank4]: File "/home/user/cache/conda/envs/unidet3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl [rank4]: return self._call_impl(*args, **kwargs) [rank4]: File "/home/user/cache/conda/envs/unidet3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl [rank4]: return forward_call(*args, **kwargs) [rank4]: File "/home/user/cache/conda/envs/unidet3d/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1632, in forward [rank4]: inputs, kwargs = self._pre_forward(*inputs, **kwargs) [rank4]: File "/home/user/cache/conda/envs/unidet3d/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1523, in _pre_forward [rank4]: if torch.is_grad_enabled() and self.reducer._rebuild_buckets(): [rank4]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by making sure all `forward` function outputs participate in calculating loss. [rank4]: If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g., list, dict, iterable). [rank4]: Parameter indices which did not receive grad for rank 4: 529 530 [rank4]: In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error.
> 
> W1119 23:25:20.007454 23287286421312 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 185073 closing signal SIGTERM `
> 
> i think most of the log are not useful, only that some parameters don't receive grad

Hi, I noticed that you encountered an issue where only one GPU was being used for training even though multiple GPUs are available. Have you found a solution or workaround for this multi-GPU training problem? If so, could you please share the steps you took or any insights you gained? Thank you!
